### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by srknhcgl** [sitronlabs/SitronLabs_Sitronix_ST75256_Arduino_Library#1]
Hi,
Could you add some example code to your repository?
thnx

**Comment by nschurando** [comment]
When using I2C to communicate with the display:
* tie `ERD` high,
* tie `RWR` high,
* tie `A0(RS)` high,
* tie `CSB` low,
* tie `D[5:4]` high,
* tie `D[3:1]` to `SDA`,
* tie `D[0]` to `SCL`,
* tie `RSTB` to a GPIO (5 in the example below),
* use `D[7]` and `D[6]` to define the device address (low in the example below).

Then you can use the following code as a basic example:
```
/* Arduino libraries */
#include <Arduino.h>
#include <Wire.h>
#include <st75256.h>

/* C/C++ libraries */
#include <stdint.h>

/* Peripherals */
#define DISPLAY_RESET_PIN 5
static st75256 m_display(192, 96);
static uint8_t m_buffer[192 * (96 / 8)];

void setup() {

    /* Setup i2c */
    Wire.begin();

    /* Setup display */
   if (m_display.setup(Wire, 0x3C, DISPLAY_RESET_PIN, m_buffer) < 0) {
        Serial.println(" [e] Failed to setup display!");
        while(1){}
    }
    if (m_display.detect() != true) {
        Serial.println(" [e] Failed to detect display!");
        while(1){}
    }

    /* Display something */
    m_display.clear();
    m_display.setTextSize(1);
    m_display.println("Hello");
    m_display.println("world");
    m_display.display();
}

void loop() {

}
```

This ST75256 library relies on the excellent [Adafruit-GFX-Library](https://github.com/adafruit/Adafruit-GFX-Library) generic graphics library from Adafruit. Adafruit has also published libraries for other displays, such as the popular SSD1306 with more detailed [examples](https://github.com/adafruit/Adafruit_SSD1306/blob/master/examples/ssd1306_128x32_i2c/ssd1306_128x32_i2c.ino) that should apply to this library.

Let me know if that helps.

**Comment by srknhcgl** [comment]
thnx for your response.
It will be great you put this code inside the doc folder in the repository.
